### PR TITLE
Fix scene save right after creation

### LINKED ISSUE #1013: scenes autosaving from streetmix result in blank screenshot
As a user importing a street from streetmix and the street is automatically saved (per [previous PR](https://github.com/3DStreet/3dstreet/pull/957): specific file is `src/index.js`) then I see an error

image

This attempted fix https://github.com/3DStreet/3dstreet/pull/1009 removed the error from user and properly saves the scene as expected, however now the screenshot is not created and results in a black box being saved as the thumbnail for most scenes

image

### PR DESCRIPTION
**Pull request by vincentfretin**
This closes #1013 fixing several issues: duplicate scene saved, title not saved, positions not saved, blank screenshot

### CODE REVIEW

File: src/components/streetplan-loader.js [hunk 1]
```diff
@@ -2,8 +2,6 @@
 import useStore from '../store.js';
 var streetplanUtils = require('../streetplan/streetplan-utils.js');
 
-const state = useStore.getState();
```
Comment (vincentfretin) [inline src/components/streetplan-loader.js:5]: Be careful `useStore.getState()` returns a snapshot of the state.

File: src/editor/lib/SceneUtils.js [hunk 2]
```diff
@@ -171,7 +189,9 @@ export async function saveScene(currentUser, doSaveAs) {
 export async function saveSceneWithScreenshot(currentUser, doSaveAs) {
   const currentSceneId = await saveScene(currentUser, doSaveAs);
   if (currentSceneId) {
-    makeScreenshot();
+    // wait a bit for models to be loaded, may not be enough...
+    await new Promise((resolve) => setTimeout(resolve, 2000));
```
Comment (vincentfretin) [inline src/editor/lib/SceneUtils.js:193]: I didn't have any issue locally, but I added that to wait a bit for models to be all loaded before taking the screenshot.
